/**
 * extract-rows.cjs
 * Parses src/data/players.ts and writes src/data/playerSeasons.ts (flat row source).
 * Run from project root: node scripts/extract-rows.cjs
 */
const fs = require('fs');
const path = require('path');

const src = fs.readFileSync(path.join(__dirname, '../src/data/players.ts'), 'utf8');

// This regex pattern (from cov2.cjs) successfully matches all 1219 players.
// We use m[0] (the full match text) to then extract name/nationality separately.
const re = /id:\s*'([^']+)'[\s\S]*?positions:\s*\[([^\]]*)\][\s\S]*?seasons:\s*\[([\s\S]*?)\][\s\S]*?primeSeason:\s*'[^']*'/g;
const seasonRe = /season:\s*'([^']+)',\s*club:\s*'([^']+)',\s*rating:\s*(\d+),\s*clApps:\s*(\d+)/g;

// Extract name from a block — handles single-quoted, double-quoted, and escaped apostrophes
function extractName(block) {
  // Double-quoted: name: "..."
  let m = block.match(/name:\s*"([^"]+)"/);
  if (m) return m[1];
  // Single-quoted with potential escaped apostrophe: name: 'Eto\'o'
  m = block.match(/name:\s*'((?:[^'\\]|\\.)*)'/);
  if (m) return m[1].replace(/\\'/g, "'");
  return null;
}

function extractNationality(block) {
  let m = block.match(/nationality:\s*"([^"]+)"/);
  if (m) return m[1];
  m = block.match(/nationality:\s*'([^']+)'/);
  if (m) return m[1];
  return null;
}

const rows = [];
let m;
while ((m = re.exec(src))) {
  const id = m[1];
  const block = m[0];
  const name = extractName(block);
  const nationality = extractNationality(block);
  const positions = m[2].split(',').map(s => s.replace(/['\s]/g, '')).filter(Boolean);
  const seasonsBlock = m[3];

  let s;
  seasonRe.lastIndex = 0;
  while ((s = seasonRe.exec(seasonsBlock))) {
    rows.push({ id, name, nationality, positions, season: s[1], club: s[2], rating: Number(s[3]), clApps: Number(s[4]) });
  }
}

const playerCount = new Set(rows.map(r => r.id)).size;
console.log(`Extracted ${rows.length} rows from ${playerCount} players.`);
if (playerCount !== 1219) console.warn(`WARNING: expected 1219 players, got ${playerCount}`);

// Spot-check the special-character names
const specialIds = ['ngolo-kante', 'ibra-inter', 'matt-oriley', 'michel-preudhomme', 'japhet-ndoram'];
for (const sid of specialIds) {
  const found = rows.find(r => r.id === sid);
  console.log(sid + ':', found ? found.name : 'NOT FOUND');
}

// Build TypeScript output
const outLines = [
  '// AUTO-GENERATED by scripts/extract-rows.cjs — do not hand-edit the header.',
  '// Add new player-seasons here as flat rows; run scripts/check.cjs to validate.',
  '',
  'export type PlayerRow = {',
  '  id: string',
  '  name: string',
  '  nationality: string',
  '  positions: string[]',
  '  season: string',
  '  club: string',
  '  rating: number',
  '  clApps: number',
  '}',
  '',
  'export const PLAYER_ROWS: PlayerRow[] = [',
];

for (const r of rows) {
  const nameStr = r.name.includes("'") ? `"${r.name}"` : `'${r.name}'`;
  const natStr = (r.nationality && r.nationality.includes("'")) ? `"${r.nationality}"` : `'${r.nationality}'`;
  const pos = r.positions.map(p => `'${p}'`).join(', ');
  outLines.push(`  { id: '${r.id}', name: ${nameStr}, nationality: ${natStr}, positions: [${pos}], season: '${r.season}', club: '${r.club}', rating: ${r.rating}, clApps: ${r.clApps} },`);
}

outLines.push(']');
outLines.push('');

fs.writeFileSync(path.join(__dirname, '../src/data/playerSeasons.ts'), outLines.join('\n'), 'utf8');
console.log(`Wrote src/data/playerSeasons.ts (${outLines.length} lines).`);
